name: Flutter Web CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Flutter environment
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests (optional)
      - name: Run tests
        run: flutter test

      # Build the Flutter web app
      - name: Build Flutter Web App
        run: flutter build web

      # Deploy to Firebase (optional)
      - name: Deploy to Firebase
        uses: wzieba/Firebase-Deploy-Action@v0.2.0
        with:
          token: ${{ secrets.FIREBASE_TOKEN }}
          project_id: calm-space-e8c20  # Replace with your Firebase project ID
          target: hosting  # Replace with your Firebase hosting target (usually 'hosting')
 